# Generated by Django 3.0.4 on 2020-03-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='huuser',
            name='goal_in_life',
            field=models.CharField(default='who cares', max_length=200),
        ),
    ]
